services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    networks:
      - demo
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${SERVICE_USER_POSTGRES}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - POSTGRES_DB=${POSTGRES_DB:-n8n}
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10

  n8n-import:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n-import
    networks:
      - demo
    environment:
      - SERVICE_FQDN_N8N_IMPORT
      - 'N8N_HOST=${SERVICE_URL_N8N}'
      - 'N8N_IMPORT_EXPORT_MODE=import'
      - 'N8N_IMPORT_DIR=/data/import'
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=${SERVICE_USER_POSTGRES}
      - DB_POSTGRESDB_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
    volumes:
      - './n8n/backup:/backup'
    depends_on:
      postgres:
        condition: service_healthy
        entrypoint: /bin/sh
    command:
      - "-c"
      - "n8n import:credentials --separate --input=/backup/credentials && n8n import:workflow --separate --input=/backup/workflows"
    healthcheck:
      test:
        - CMD-SHELL
        - '[ "$(ls -A /data/import)" ] || exit 1'
      interval: 10s
      timeout: 5s
      retries: 3

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    networks:
      - demo
    restart: unless-stopped
    ports:
      - "5680:5678"
    environment:
      - SERVICE_FQDN_N8N_5680
      - 'N8N_EDITOR_BASE_URL=${SERVICE_FQDN_N8N}'
      - 'WEBHOOK_URL=${SERVICE_FQDN_N8N}'
      - 'N8N_HOST=${SERVICE_URL_N8N}'
      - 'GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-Europe/Berlin}'
      - 'TZ=${TZ:-Europe/Berlin}'
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=$SERVICE_USER_POSTGRES
      - DB_POSTGRESDB_SCHEMA=public
      - DB_POSTGRESDB_PASSWORD=$SERVICE_PASSWORD_POSTGRES
    volumes:
      - n8n_storage:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget -qO- http://127.0.0.1:5678/'
      interval: 5s
      timeout: 20s
      retries: 10

  flowise:
    image: flowiseai/flowise:latest
    container_name: flowise
    networks:
      - demo
    restart: unless-stopped
    ports:
      - "3003:3001"
    environment:
      - SERVICE_FQDN_FLOWISE_3003
      - 'DEBUG=${DEBUG:-false}'
      - 'DISABLE_FLOWISE_TELEMETRY=${DISABLE_FLOWISE_TELEMETRY:-true}'
      - 'PORT=${PORT:-3001}'
      - DATABASE_PATH=/root/.flowise/db.sqlite3
      - APIKEY_PATH=/root/.flowise
      - SECRETKEY_PATH=/root/.flowise
      - LOG_PATH=/root/.flowise/logs
      - BLOB_STORAGE_PATH=/root/.flowise/storage
      - 'FLOWISE_USERNAME=${SERVICE_USER_FLOWISE}' # Username for Flowise authentication
      - 'FLOWISE_PASSWORD=${SERVICE_PASSWORD_FLOWISE}' # Password for Flowise authentication
    volumes:
      - flowise_data:/root/.flowise/  
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget -qO- http://127.0.0.1:3001 || exit 1'
      interval: 5s
      timeout: 5s
      retries: 3

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    networks:
      - demo
    restart: unless-stopped
    ports:
      - "6335:6333"
    environment:
      - SERVICE_FQDN_QDRANT_6335
      - 'QDRANT__SERVICE__API_KEY=${SERVICE_PASSWORD_QDRANTAPIKEY}'
    volumes:
      - qdrant_storage:/qdrant/storage
    healthcheck:
      test:
        - CMD-SHELL
        - "bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  demo:

volumes:
  n8n_storage:
  postgres_storage:
  flowise_data:
  qdrant_storage:
